name: Deploy corona incidence viewer
on:
   push:
      branches:
      - main
   pull_request:
      branches:
      - main

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
           node-version: [14.x]
           # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
      - name: Install necessary packages
        run: npm install
      - name: Run 'npm audit fix' 
        run: npm audit fix
      - name: Build Web content
        run: npm run build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'Mugetsu15'
          destination-repository-name: 'corona'
          user-email: admin@maxuniverse.de
          target-branch: gh-pages
